fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "bdealvarenga@gmail.com"
        sender_name: "Bernard"
    registration:
        confirmation:
            enabled: true
        form:
            type: App\Form\RegistrationType